quiz/urls.py
from django.contrib import admin
from django.urls import path, include

from quizapp.views import index, registration


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index, name='index'),
    path('catalog/', include('quizapp.urls', namespace='catalog')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('registration/', registration, name='registration'),
]

quizapp/urls.py
from django.urls import path

from quizapp.views import catalogs, test, get_question

app_name = 'quizapp'

urlpatterns = [

    path('', catalogs, name='catalog'),
    path('<int:pk>/', catalogs, name='catalog'),
    path('test/<int:pk>/', test, name='test'),
    path('test/<int:test_id>/questions/<int:pk>/', get_question, name='question'),
]

quizapp/models.py
from django.db import models
from django.template.defaultfilters import truncatewords
from django.contrib.auth.models import User

from model_utils.managers import InheritanceManager


class QuizCategory(models.Model):
    name = models.CharField('название категории', max_length=64, unique=True)
    description = models.TextField('описание', blank=True, null=True)

    class Meta:
        verbose_name = 'категория тестов'
        verbose_name_plural = 'категории тестов'

    def __str__(self):
        return self.name


class Quiz(models.Model):
    category = models.ForeignKey(QuizCategory, on_delete=models.CASCADE, verbose_name='категория')
    title = models.CharField('название теста', max_length=64, unique=True)
    description = models.TextField('описание', blank=True, null=True)

    class Meta:
        verbose_name = 'тест'
        verbose_name_plural = 'тесты'

    def __str__(self):
        return self.title


class Question(models.Model):
    CHOICES_TYPE = [
        ("1", "Ответ с выбором одного варианта"),
        ("2", "Ответ с выбором нескольких вариантов"),
    ]

    objects = InheritanceManager()

    test = models.ForeignKey(
        verbose_name="Тесты",
        to=Quiz,
        on_delete=models.CASCADE,
        related_name="questions",
    )
    description = models.TextField(verbose_name="Вопрос")
    type_question = models.CharField(
        verbose_name="Тип вопроса", choices=CHOICES_TYPE, max_length=2
    )

    class Meta:
        verbose_name = "Вопрос"
        verbose_name_plural = "Вопросы"
        unique_together = (("test", "description", "type_question"),)

    def __str__(self):
        return f"{self.description}"

    @property
    def short_description(self):
        return truncatewords(self.description, 5)


class Answer(models.Model):
    text = models.TextField(verbose_name="Ответ", blank=False)
    question = models.ForeignKey(verbose_name="Вопрос",  to=Question, on_delete=models.CASCADE, related_name="answers")
    user = models.ForeignKey(verbose_name="Пользователь", to=User, blank=True, null=True, on_delete=models.CASCADE,
                             related_name="user_answers",)
    is_admin = models.BooleanField(default=True)
    is_right = models.BooleanField(verbose_name="Правильный ответ", default=False)

    class Meta:
        ordering = ['?']
        verbose_name = "Ответ"
        verbose_name_plural = "Ответы"
        unique_together = (("text", "question", "user", "is_admin"),)

    def __str__(self):
        return f"{self.text}"

    @property
    def short_text(self):
        return truncatewords(self.text, 5)

quizapp/forms.py
from django import forms
from django.core.exceptions import ValidationError


class QuestionForm(forms.Form):
    choices = forms.MultipleChoiceField(label='', required=False, widget=forms.CheckboxSelectMultiple)
    instance = {}

    def is_valid(self):
        if len(self.data) == 1 or len(self.data) == 0:
            return False
        else:
            return True

    def clean(self):
        if len(self.data) == 1:
            raise ValidationError("Вы не выбрали ответ")

    def user_answer_instance(self):
        self.instance.update(self.data)

    def clear_instance(self):
        self.instance.clear()

quizapp/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from quizapp.models import Quiz, QuizCategory, Answer
from quizapp.forms import QuestionForm

from quiz.forms import UserRegistrationForm


def index(request):
    return render(request, 'quizapp/index.html', {'title': 'Главная'})


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Поздравляем! Регистрация прошла успешно.')
            return HttpResponseRedirect(reverse('login'))
        else:
            print(form.errors)
    else:
        form = UserRegistrationForm()
    context = {
        'title': 'регистрация',
        'form': form
    }
    return render(request, 'registration/registration.html', context)


@login_required
def catalogs(request, pk=0):
    if pk:
        tests = Quiz.objects.filter(category_id=pk)
    else:
        tests = Quiz.objects.all()
    context = {
        'title': 'Тесты',
        'tests': tests,
        'catalog': QuizCategory.objects.all(),
    }
    return render(request, 'quizapp/tests.html', context)


@login_required
def test(request, pk):
    quiz = Quiz.objects.filter(id=pk).first()
    questions = quiz.questions.all()
    try:
        question = questions.first()
        question_pk = question.pk
    except (IndexError, AttributeError):
        question = 'нет вопросов'
        question_pk = 0

    context = {
        'title': quiz.title,
        'question': question,
        'category': quiz.category.name,
        'description': quiz.description,
        'questions_count': questions.count(),
        'test_id': pk,
        'question_pk': question_pk,
        'pk': 0,
    }
    return render(request, 'test/index.html', context)


@login_required
def get_question(request, test_id, pk):

    if request.method == "POST":
        form = QuestionForm(request.POST)
    else:
        form = QuestionForm()

    if form.is_valid():
        pk += 1

    form.user_answer_instance()
    quiz = Quiz.objects.get(pk=test_id)

    try:
        question = quiz.questions.all()[pk]
    except IndexError:
        return get_results(request, test_id, form)

    context = {
        'title': 'Вопросы',
        'question': question,
        'description': question.description,
        'answers': question.answers.all(),
        'test_id': test_id,
        'pk': pk,
        'form': form,
    }

    return render(request, 'test/question.html', context)


def get_results(request, test_id, form):
    quiz = Quiz.objects.get(pk=test_id)
    results = form.instance
    results.pop('csrfmiddlewaretoken')
    answers_list = [i[0] for i in results.values()]
    count_rights = Answer.objects.filter(question_id__in=quiz.questions.all()).filter(is_right=1).count()
    context = {
        'title': 'Результаты',
        'questions_count': quiz.questions.count(),
        'total_answers': len(results),
        'rights': answers_list.count('True'),
        'wrongs': answers_list.count('False'),
        'all_rights': int(answers_list.count('True') / count_rights * 100),
    }
    form.clear_instance()
    return render(request, 'test/result.html', context)

templates/quizapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title|capfirst }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}

</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Главная</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'quizapp:catalog' %}">Каталог тестов <i class="fas fa-align-justify"></i>
                    </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-user-circle"></i>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>
                                <a class="dropdown-item" href="{% url 'logout' %}">
                                    Выйти
                                </a>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %} {% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
{% block js %} {% endblock %}

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

templates/quizapp/index.html
{% extends 'quizapp/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h1 class="mt-5">Тестовое задание для Fortech</h1>
                    <p>
                        Простой сервис проведения тестирования по каким-либо темам. Тесты с вариантами
                        ответов, один или несколько вариантов должны быть правильными. Тесты группируются в наборы
                        тестов, которые затем пользователь может проходить и видеть свой результат.
                    </p>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/quizapp/tests.html
{% extends 'quizapp/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/tests.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        {% if user.is_authenticated %}
            <div class="row">
                <div class="col-lg-3">
                    <h1 class="my-4">Каталог</h1>
                    <div class="list-group">
                     <a href="{% url 'quizapp:catalog' 0 %}" class="list-group-item">Все категории</a>
                        {% for category in catalog %}
                            <a href="{% url 'quizapp:catalog' category.pk %}" class="list-group-item">{{ category.name }}</a>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-lg-9">
                    <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel"></div>
                    <div class="row">
                        {% if tests %}
                            {% for test in tests %}
                                <div class="col-lg-4 col-md-6 mb-4">
                                    <div class="card h-100">
                                        <div class="card-body">
                                            <h4 class="card-title">
                                                <a href="{% url 'quizapp:test' test.pk %}">{{ test.title }}</a>
                                            </h4>
                                            <p class="card-text">{{ test.description }}</p>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        {% else %}
                            <h4 class="card-title" style="color: red">
                                В данной катеогрии нет тестов
                            </h4>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% else %}
            <div class="text-center">
                <div class="card h-100">
                    <div class="card-body">
                        <h4 class="card-title">
                            Вы не авторизованы
                        </h4>
                        <a class="nav-link" href="{% url 'login' %}">Войти?</a>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}